version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: project
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432:5432/project
    volumes:
      - ./backend:/app
    ports:
    - '4000:4000'
    depends_on:
      - db

  frontend:
     build: ./frontend/front
     volumes:
       - ./front:/app
     ports:
       - '3000:3000'
volumes:
  db-data:
